name = "steamapp"
compatibility_date = "2026-08-31"

main = "src/index.js"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "steam-games"
database_id = "77317d10-6069-447f-8d36-b3c92eded4e7"